name: Security Scan

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Gitleaks (secrets scan)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: "accept"

      - name: Run Trivy vulnerability scanner (files and dependencies)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          severity: CRITICAL,HIGH
          exit-code: 0

      - name: Scan Dockerfile with Trivy (if present)
        run: |
          if [ -f Dockerfile ]; then
            docker run --rm -v $(pwd):/src aquasec/trivy image --severity CRITICAL,HIGH --no-progress -q -f table -i /src/Dockerfile || true
          else
            echo "No Dockerfile found, skipping image scan."
          fi

      - name: Run npm audit on demo-app
        working-directory: demo-app
        run: |
          npm install --omit=dev
          npm audit --audit-level=high || true
