name: Security Scan

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  security-checks:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.result.outcome }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh -y
          gh auth status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Gitleaks (secrets scan)
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: "accept"

      - name: Run Trivy vulnerability scanner
        id: trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Scan Dockerfile with Trivy (if present)
        id: trivy-docker
        run: |
          if [ -f Dockerfile ]; then
            docker run --rm -v $(pwd):/src aquasec/trivy image --severity CRITICAL,HIGH --no-progress -q -f table -i /src/Dockerfile
          else
            echo "No Dockerfile found, skipping image scan."
          fi

      - name: Run npm audit on demo-app
        id: npm-audit
        working-directory: demo-app
        run: |
          npm install --omit=dev
          npm audit --audit-level=high

      - name: Mark checks complete
        id: result
        run: echo "All checks complete"

  security-gate:
    runs-on: ubuntu-latest
    needs: security-checks
    if: always()
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh -y
          gh auth status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Evaluate no-block label override
        run: |
          echo "Checking for 'no-block' label..."
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            LABELS=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name')
            echo "Labels: $LABELS"
            if echo "$LABELS" | grep -q "no-block"; then
              echo "'no-block' label found. Overriding failure."
              exit 0
            fi
          fi

          echo "Checking result of security-checks..."
          if [ "${{ needs.security-checks.result }}" != "success" ]; then
            echo "Security checks failed and no override present. Blocking merge."
            exit 1
          fi
          echo "All security checks passed or override applied."
