name: Security Scan

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks via action (full source scan)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-git --redact --report-format sarif --report-path gitleaks.sarif --exit-code 1
        env:
          GITLEAKS_LICENSE: accept
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Gitleaks SARIF
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-results
          path: gitleaks.sarif
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1
      - name: Scan Dockerfile
        run: |
          if [ -f Dockerfile ]; then
            docker run --rm -v $(pwd):/src aquasec/trivy image --severity CRITICAL,HIGH --no-progress -q -f table -i /src/Dockerfile
          else
            echo "No Dockerfile found."
          fi

  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run npm audit
        working-directory: demo-app
        run: |
          npm install --omit=dev
          npm audit --audit-level=high

  no-block-check:
    runs-on: ubuntu-latest
    needs: [gitleaks, trivy, npm-audit]
    if: always()
    steps:
      - uses: actions/checkout@v3

      - name: Allow merge if 'no-block' label is present
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Evaluating 'no-block' label override..."
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            LABELS=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name')
            echo "Labels: $LABELS"
            if echo "$LABELS" | grep -q "no-block"; then
              echo "'no-block' label found. Allowing merge."
              exit 0
            fi
          fi

          # Check if any required job failed
          if [ "${{ needs.gitleaks.result }}" != "success" ] || \
             [ "${{ needs.trivy.result }}" != "success" ] || \
             [ "${{ needs.npm-audit.result }}" != "success" ]; then
            echo "Checks failed. Merge blocked."
            exit 1
          fi

          echo "All checks passed."
